blank_issues_enabled: false
contact_links:
  - name: Questions & Discussion
    url: https://github.com/rgdupree2/learn-github/discussions
    about: Ask questions in Discussions instead of opening an issue